=== Sinsam0105/triplea-rebased/maps/small_front_poland/map/games/game.dtd
<!ELEMENT game (info, loader?, triplea?, diceSides?, map, resourceList?, playerList, unitList?, relationshipTypes?, territoryEffectList?, gamePlay, production?, technology?, attachmentList?, initialize?, propertyList?)>
<!ELEMENT info EMPTY>
<!ATTLIST info name CDATA #REQUIRED version CDATA #IMPLIED>
<!ELEMENT loader EMPTY>
<!ATTLIST loader javaClass CDATA #REQUIRED>
<!ELEMENT triplea EMPTY>
<!ATTLIST triplea minimumVersion CDATA #REQUIRED>
<!ELEMENT diceSides EMPTY>
<!ATTLIST diceSides value CDATA #REQUIRED>

<!ELEMENT map (territory+, connection*)>
<!ELEMENT territory EMPTY>
<!ATTLIST territory name CDATA #REQUIRED water (true|false) "false">
<!ELEMENT connection EMPTY>
<!ATTLIST connection t1 CDATA #REQUIRED t2 CDATA #REQUIRED>

<!ELEMENT resourceList (resource+)>
<!ELEMENT resource EMPTY>
<!ATTLIST resource name ID #REQUIRED isDisplayedFor CDATA #IMPLIED>

<!ELEMENT playerList (player+, alliance*)>
<!ELEMENT player EMPTY>
<!ATTLIST player name ID #REQUIRED optional (true|false) "false" canBeDisabled (true|false) "false" defaultType (Human|AI|DoesNothing) "Human" isHidden (true|false) "false">
<!ELEMENT alliance EMPTY>
<!ATTLIST alliance player IDREF #REQUIRED alliance CDATA #REQUIRED>

<!ELEMENT unitList (unit+)>
<!ELEMENT unit EMPTY>
<!ATTLIST unit name ID #REQUIRED>

<!ELEMENT relationshipTypes (relationshipType+)>
<!ELEMENT relationshipType EMPTY>
<!ATTLIST relationshipType name ID #REQUIRED>

<!ELEMENT territoryEffectList (territoryEffect+)>
<!ELEMENT territoryEffect EMPTY>
<!ATTLIST territoryEffect name ID #REQUIRED>

<!ELEMENT gamePlay (delegate+, sequence, offset?)>
<!ELEMENT delegate EMPTY>
<!ATTLIST delegate name ID #REQUIRED javaClass CDATA #REQUIRED display CDATA #IMPLIED>
<!ELEMENT sequence (step+)>
<!ELEMENT step (stepProperty*)>
<!ATTLIST step name ID #REQUIRED delegate IDREF #REQUIRED player IDREF #IMPLIED maxRunCount CDATA #IMPLIED display CDATA #IMPLIED>
<!ELEMENT stepProperty EMPTY>
<!ATTLIST stepProperty name CDATA #REQUIRED value CDATA #REQUIRED>
<!ELEMENT offset EMPTY>
<!ATTLIST offset round CDATA #REQUIRED>

<!ELEMENT production ANY>
<!ELEMENT technology ANY>

<!ELEMENT attachmentList (attachment+)>
<!ELEMENT attachment (option+)>
<!ATTLIST attachment foreach CDATA #IMPLIED name CDATA #REQUIRED attachTo CDATA #REQUIRED javaClass CDATA #REQUIRED type (unitType|territory|resource|player|relationship|territoryEffect|technology) "unitType">
<!ELEMENT option EMPTY>
<!ATTLIST option name CDATA #REQUIRED value CDATA #REQUIRED count CDATA "">

<!ELEMENT initialize (ownerInitialize?, unitInitialize?, resourceInitialize?, relationshipInitialize?)>
<!ELEMENT ownerInitialize (territoryOwner+)>
<!ELEMENT territoryOwner EMPTY>
<!ATTLIST territoryOwner territory CDATA #REQUIRED owner IDREF #REQUIRED>
<!ELEMENT unitInitialize (unitPlacement*, heldUnits*)>
<!ELEMENT unitPlacement EMPTY>
<!ATTLIST unitPlacement unitType IDREF #REQUIRED territory CDATA #REQUIRED quantity CDATA #REQUIRED owner IDREF #IMPLIED hitsTaken CDATA #IMPLIED unitDamage CDATA #IMPLIED>
<!ELEMENT heldUnits EMPTY>
<!ATTLIST heldUnits unitType IDREF #REQUIRED player IDREF #REQUIRED quantity CDATA #REQUIRED>
<!ELEMENT resourceInitialize (resourceGiven+)>
<!ELEMENT resourceGiven EMPTY>
<!ATTLIST resourceGiven player IDREF #REQUIRED resource IDREF #REQUIRED quantity CDATA #REQUIRED>
<!ELEMENT relationshipInitialize (relationship+)>
<!ELEMENT relationship EMPTY>
<!ATTLIST relationship player1 IDREF #REQUIRED player2 IDREF #REQUIRED type IDREF #REQUIRED roundValue CDATA #REQUIRED>

<!ELEMENT propertyList (property*)>
<!ELEMENT property (boolean?, string?, number?, value?)>
<!ATTLIST property value CDATA "" name CDATA #REQUIRED editable (true|false) "false" player CDATA "">
<!ELEMENT value (#PCDATA)>
<!ELEMENT boolean EMPTY>
<!ELEMENT string EMPTY>
<!ELEMENT number EMPTY>
<!ATTLIST number max CDATA #REQUIRED min CDATA #REQUIRED>

=== Sinsam0105/triplea-rebased/game-app/smoke-testing/src/test/resources/map-xmls/Small_Front_Poland.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game SYSTEM "game.dtd">
<game>
  <info name="Small Front: Vistula Withdrawal" version="0.1"/>
  <loader javaClass="games.strategy.triplea.TripleA"/>
  <triplea minimumVersion="2.7.0"/>
  <diceSides value="6"/>

  <map>
    <territory name="Breslau"/>
    <territory name="Brest"/>
    <territory name="Bydgoszcz"/>
    <territory name="Czestochowa"/>
    <territory name="Danzig"/>
    <territory name="Deblin"/>
    <territory name="Frankfurt Oder"/>
    <territory name="Gdynia"/>
    <territory name="Grudziadz"/>
    <territory name="Kalisz"/>
    <territory name="Katowice"/>
    <territory name="Kielce"/>
    <territory name="Krakow"/>
    <territory name="Kutno"/>
    <territory name="Lodz"/>
    <territory name="Lublin"/>
    <territory name="Lukow"/>
    <territory name="Lwow"/>
    <territory name="Marienwerder"/>
    <territory name="Modlin"/>
    <territory name="Oppeln"/>
    <territory name="Piotrkow"/>
    <territory name="Plock"/>
    <territory name="Poznan"/>
    <territory name="Radom"/>
    <territory name="Sandomierz"/>
    <territory name="Schneidemuhl"/>
    <territory name="Siedlce"/>
    <territory name="Tarnow"/>
    <territory name="Tczew"/>
    <territory name="Teschen"/>
    <territory name="Torun"/>
    <territory name="Warsaw"/>
    <territory name="Wloclawek"/>
    <territory name="Zamosc"/>
    <connection t1="Breslau" t2="Frankfurt Oder"/>
    <connection t1="Breslau" t2="Kalisz"/>
    <connection t1="Breslau" t2="Oppeln"/>
    <connection t1="Breslau" t2="Poznan"/>
    <connection t1="Brest" t2="Lublin"/>
    <connection t1="Brest" t2="Lukow"/>
    <connection t1="Brest" t2="Siedlce"/>
    <connection t1="Brest" t2="Zamosc"/>
    <connection t1="Bydgoszcz" t2="Grudziadz"/>
    <connection t1="Bydgoszcz" t2="Poznan"/>
    <connection t1="Bydgoszcz" t2="Schneidemuhl"/>
    <connection t1="Bydgoszcz" t2="Tczew"/>
    <connection t1="Bydgoszcz" t2="Torun"/>
    <connection t1="Bydgoszcz" t2="Wloclawek"/>
    <connection t1="Czestochowa" t2="Katowice"/>
    <connection t1="Czestochowa" t2="Kielce"/>
    <connection t1="Czestochowa" t2="Krakow"/>
    <connection t1="Czestochowa" t2="Lodz"/>
    <connection t1="Czestochowa" t2="Piotrkow"/>
    <connection t1="Danzig" t2="Gdynia"/>
    <connection t1="Danzig" t2="Marienwerder"/>
    <connection t1="Danzig" t2="Tczew"/>
    <connection t1="Deblin" t2="Lublin"/>
    <connection t1="Deblin" t2="Lukow"/>
    <connection t1="Deblin" t2="Radom"/>
    <connection t1="Deblin" t2="Sandomierz"/>
    <connection t1="Deblin" t2="Warsaw"/>
    <connection t1="Deblin" t2="Zamosc"/>
    <connection t1="Frankfurt Oder" t2="Poznan"/>
    <connection t1="Frankfurt Oder" t2="Schneidemuhl"/>
    <connection t1="Gdynia" t2="Grudziadz"/>
    <connection t1="Gdynia" t2="Tczew"/>
    <connection t1="Grudziadz" t2="Tczew"/>
    <connection t1="Grudziadz" t2="Torun"/>
    <connection t1="Kalisz" t2="Katowice"/>
    <connection t1="Kalisz" t2="Lodz"/>
    <connection t1="Kalisz" t2="Poznan"/>
    <connection t1="Katowice" t2="Krakow"/>
    <connection t1="Katowice" t2="Oppeln"/>
    <connection t1="Katowice" t2="Teschen"/>
    <connection t1="Kielce" t2="Krakow"/>
    <connection t1="Kielce" t2="Piotrkow"/>
    <connection t1="Kielce" t2="Sandomierz"/>
    <connection t1="Kielce" t2="Tarnow"/>
    <connection t1="Krakow" t2="Teschen"/>
    <connection t1="Kutno" t2="Lodz"/>
    <connection t1="Kutno" t2="Modlin"/>
    <connection t1="Kutno" t2="Piotrkow"/>
    <connection t1="Kutno" t2="Plock"/>
    <connection t1="Kutno" t2="Radom"/>
    <connection t1="Kutno" t2="Wloclawek"/>
    <connection t1="Lodz" t2="Piotrkow"/>
    <connection t1="Lodz" t2="Wloclawek"/>
    <connection t1="Lublin" t2="Lukow"/>
    <connection t1="Lublin" t2="Zamosc"/>
    <connection t1="Lukow" t2="Siedlce"/>
    <connection t1="Lukow" t2="Warsaw"/>
    <connection t1="Lwow" t2="Zamosc"/>
    <connection t1="Marienwerder" t2="Schneidemuhl"/>
    <connection t1="Marienwerder" t2="Tczew"/>
    <connection t1="Modlin" t2="Plock"/>
    <connection t1="Modlin" t2="Radom"/>
    <connection t1="Modlin" t2="Siedlce"/>
    <connection t1="Modlin" t2="Warsaw"/>
    <connection t1="Oppeln" t2="Teschen"/>
    <connection t1="Piotrkow" t2="Radom"/>
    <connection t1="Piotrkow" t2="Sandomierz"/>
    <connection t1="Plock" t2="Torun"/>
    <connection t1="Plock" t2="Wloclawek"/>
    <connection t1="Poznan" t2="Schneidemuhl"/>
    <connection t1="Radom" t2="Sandomierz"/>
    <connection t1="Radom" t2="Warsaw"/>
    <connection t1="Sandomierz" t2="Tarnow"/>
    <connection t1="Schneidemuhl" t2="Tczew"/>
    <connection t1="Siedlce" t2="Warsaw"/>
    <connection t1="Torun" t2="Wloclawek"/>
  </map>

  <resourceList>
    <resource name="PUs"/>
  </resourceList>

  <playerList>
    <player name="Germans" optional="false" defaultType="Human"/>
    <player name="Poland" optional="false" defaultType="Human"/>
    <alliance player="Germans" alliance="Axis"/>
    <alliance player="Poland" alliance="Allies"/>
  </playerList>

  <unitList>
    <unit name="infantry"/>
    <unit name="polishInfantry"/>
    <unit name="polishArtillery"/>
    <unit name="cavalry"/>
    <unit name="armour"/>
    <unit name="mechanized"/>
    <unit name="selfPropelledArtillery"/>
  </unitList>

  <relationshipTypes>
    <relationshipType name="War"/>
    <relationshipType name="Allied"/>
  </relationshipTypes>

  <territoryEffectList>
    <territoryEffect name="Open"/>
    <territoryEffect name="Forest"/>
    <territoryEffect name="Town"/>
  </territoryEffectList>

  <gamePlay>
    <delegate name="initialization" javaClass="games.strategy.triplea.delegate.InitializationDelegate" display="Initialize"/>
    <delegate name="reinforcement" javaClass="games.strategy.triplea.delegate.FixedReinforcementDelegate" display="Fixed Reinforcements"/>
    <delegate name="supply" javaClass="games.strategy.triplea.delegate.SupplyDelegate" display="Supply"/>
    <delegate name="move" javaClass="games.strategy.triplea.delegate.SupplyAwareMoveDelegate" display="Move"/>
    <delegate name="battle" javaClass="games.strategy.triplea.delegate.BattleDelegate" display="Battle"/>
    <delegate name="endTurn" javaClass="games.strategy.triplea.delegate.NoPUEndTurnDelegate" display="End Turn"/>
    <delegate name="endRound" javaClass="games.strategy.triplea.delegate.SmallFrontEndRoundDelegate" display="End Round"/>

    <sequence>
      <step name="initializationStep" delegate="initialization" maxRunCount="1"/>

      <step name="germanReinforcement" delegate="reinforcement" player="Germans"/>
      <step name="germanSupply" delegate="supply" player="Germans"/>
      <step name="germanCombatMove" delegate="move" player="Germans" display="Combat Move"/>
      <step name="germanBattle" delegate="battle" player="Germans"/>
      <step name="germanNonCombatMove" delegate="move" player="Germans" display="Redeployment">
        <stepProperty name="nonCombatMove" value="true"/>
        <stepProperty name="removeAirThatCanNotLand" value="false"/>
      </step>
      <step name="germanEndTurn" delegate="endTurn" player="Germans"/>

      <step name="polishReinforcement" delegate="reinforcement" player="Poland"/>
      <step name="polishSupply" delegate="supply" player="Poland"/>
      <step name="polishCombatMove" delegate="move" player="Poland" display="Combat Move"/>
      <step name="polishBattle" delegate="battle" player="Poland"/>
      <step name="polishNonCombatMove" delegate="move" player="Poland" display="Redeployment">
        <stepProperty name="nonCombatMove" value="true"/>
        <stepProperty name="removeAirThatCanNotLand" value="false"/>
      </step>
      <step name="polishEndTurn" delegate="endTurn" player="Poland"/>

      <step name="endRoundStep" delegate="endRound"/>
    </sequence>
  </gamePlay>
  <attachmentList>
    <attachment name="relationshipTypeAttachment" attachTo="War" javaClass="games.strategy.triplea.attachments.RelationshipTypeAttachment" type="relationship">
      <option name="archeType" value="war"/>
    </attachment>
    <attachment name="relationshipTypeAttachment" attachTo="Allied" javaClass="games.strategy.triplea.attachments.RelationshipTypeAttachment" type="relationship">
      <option name="archeType" value="allied"/>
    </attachment>

    <attachment name="territoryEffectAttachment" attachTo="Open" javaClass="games.strategy.triplea.attachments.TerritoryEffectAttachment" type="territoryEffect">
      <option name="maxGroundBattleRounds" value="4"/>
      <option name="maxAirBattleRounds" value="1"/>
      <option name="stackCapacity" value="7"/>
    </attachment>
    <attachment name="territoryEffectAttachment" attachTo="Forest" javaClass="games.strategy.triplea.attachments.TerritoryEffectAttachment" type="territoryEffect">
      <option name="maxGroundBattleRounds" value="2"/>
      <option name="maxAirBattleRounds" value="1"/>
      <option name="stackCapacity" value="5"/>
    </attachment>
    <attachment name="territoryEffectAttachment" attachTo="Town" javaClass="games.strategy.triplea.attachments.TerritoryEffectAttachment" type="territoryEffect">
      <option name="maxGroundBattleRounds" value="3"/>
      <option name="maxAirBattleRounds" value="1"/>
      <option name="stackCapacity" value="6"/>
    </attachment>

    <attachment name="unitAttachment" attachTo="infantry" javaClass="games.strategy.triplea.attachments.UnitAttachment" type="unitType">
      <option name="movement" value="1"/>
      <option name="combatMovement" value="1"/>
      <option name="redeploymentMovement" value="1"/>
      <option name="attack" value="1"/>
      <option name="defense" value="2"/>
      <option name="isInfantry" value="true"/>
      <option name="artillerySupportable" value="true"/>
      <option name="stackCost" value="1"/>
      <option name="tuv" value="3"/>
    </attachment>
